import 'dart:io';

const _alphabet =
    '@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_ !"#\$%&\'()*+,-./0123456789:;<=>?';

void main(List<String> arguments) {
  final output = File(
    arguments.firstOrNull ?? 'apps/mobile/assets/replay/solent_ais.nmea',
  );
  output.parent.createSync(recursive: true);
  final sentences = <String>[
    ..._type5(
      mmsi: 235000111,
      name: 'SOLENT FERRY',
      callSign: 'MFA111',
      shipType: 60,
      sequence: '1',
    ),
    _type24a(mmsi: 235000222, name: 'SEA BREEZE'),
    _type24b(mmsi: 235000222, callSign: 'MFA222', shipType: 36),
    ..._type5(
      mmsi: 235000333,
      name: 'HARBOUR TUG',
      callSign: 'MFA333',
      shipType: 52,
      sequence: '2',
    ),
    _type1(
      mmsi: 235000111,
      latitude: 50.8010,
      longitude: -1.3000,
      speedKnots: 12.4,
      courseDegrees: 92.0,
      headingDegrees: 91,
      second: 10,
      navigationStatus: 0,
    ),
    _type18(
      mmsi: 235000222,
      latitude: 50.7900,
      longitude: -1.2700,
      speedKnots: 5.8,
      courseDegrees: 230.0,
      headingDegrees: 231,
      second: 11,
    ),
    _type1(
      mmsi: 235000333,
      latitude: 50.8050,
      longitude: -1.2600,
      speedKnots: 3.2,
      courseDegrees: 310.0,
      headingDegrees: 309,
      second: 12,
      navigationStatus: 3,
    ),
    _type1(
      mmsi: 235000111,
      latitude: 50.8012,
      longitude: -1.2960,
      speedKnots: 12.5,
      courseDegrees: 92.0,
      headingDegrees: 91,
      second: 20,
      navigationStatus: 0,
    ),
    _type18(
      mmsi: 235000222,
      latitude: 50.7888,
      longitude: -1.2720,
      speedKnots: 5.7,
      courseDegrees: 230.0,
      headingDegrees: 231,
      second: 21,
    ),
    _type1(
      mmsi: 235000333,
      latitude: 50.8060,
      longitude: -1.2610,
      speedKnots: 3.0,
      courseDegrees: 310.0,
      headingDegrees: 309,
      second: 22,
      navigationStatus: 3,
    ),
  ];
  output.writeAsStringSync(
    '# Synthetic, non-live AIS replay for Tide and Seek tests.\n'
    '# Generated by tools/ais/build_replay_fixture.dart.\n'
    '${sentences.join('\n')}\n',
  );
  stdout.writeln('Wrote ${sentences.length} sentences to ${output.path}');
}

String _type1({
  required int mmsi,
  required double latitude,
  required double longitude,
  required double speedKnots,
  required double courseDegrees,
  required int headingDegrees,
  required int second,
  required int navigationStatus,
}) {
  final bits = _Bits(168)
    ..unsigned(0, 6, 1)
    ..unsigned(8, 30, mmsi)
    ..unsigned(38, 4, navigationStatus)
    ..signed(42, 8, -128)
    ..unsigned(50, 10, (speedKnots * 10).round())
    ..unsigned(60, 1, 1)
    ..signed(61, 28, (longitude * 600000).round())
    ..signed(89, 27, (latitude * 600000).round())
    ..unsigned(116, 12, (courseDegrees * 10).round())
    ..unsigned(128, 9, headingDegrees)
    ..unsigned(137, 6, second);
  return _single(bits.payload());
}

String _type18({
  required int mmsi,
  required double latitude,
  required double longitude,
  required double speedKnots,
  required double courseDegrees,
  required int headingDegrees,
  required int second,
}) {
  final bits = _Bits(168)
    ..unsigned(0, 6, 18)
    ..unsigned(8, 30, mmsi)
    ..unsigned(46, 10, (speedKnots * 10).round())
    ..unsigned(56, 1, 1)
    ..signed(57, 28, (longitude * 600000).round())
    ..signed(85, 27, (latitude * 600000).round())
    ..unsigned(112, 12, (courseDegrees * 10).round())
    ..unsigned(124, 9, headingDegrees)
    ..unsigned(133, 6, second);
  return _single(bits.payload());
}

List<String> _type5({
  required int mmsi,
  required String name,
  required String callSign,
  required int shipType,
  required String sequence,
}) {
  final bits = _Bits(424)
    ..unsigned(0, 6, 5)
    ..unsigned(8, 30, mmsi)
    ..text(70, 42, callSign)
    ..text(112, 120, name)
    ..unsigned(232, 8, shipType);
  final encoded = bits.payload();
  final split = encoded.payload.length ~/ 2;
  return [
    _sentence('AIVDM,2,1,$sequence,A,${encoded.payload.substring(0, split)},0'),
    _sentence(
      'AIVDM,2,2,$sequence,A,${encoded.payload.substring(split)},${encoded.fillBits}',
    ),
  ];
}

String _type24a({required int mmsi, required String name}) {
  final bits = _Bits(160)
    ..unsigned(0, 6, 24)
    ..unsigned(8, 30, mmsi)
    ..unsigned(38, 2, 0)
    ..text(40, 120, name);
  return _single(bits.payload());
}

String _type24b({
  required int mmsi,
  required String callSign,
  required int shipType,
}) {
  final bits = _Bits(168)
    ..unsigned(0, 6, 24)
    ..unsigned(8, 30, mmsi)
    ..unsigned(38, 2, 1)
    ..unsigned(40, 8, shipType)
    ..text(90, 42, callSign);
  return _single(bits.payload());
}

String _single(({String payload, int fillBits}) encoded) =>
    _sentence('AIVDM,1,1,,A,${encoded.payload},${encoded.fillBits}');

String _sentence(String body) {
  var checksum = 0;
  for (final code in body.codeUnits) {
    checksum ^= code;
  }
  return '!$body*${checksum.toRadixString(16).padLeft(2, '0').toUpperCase()}';
}

class _Bits {
  _Bits(int length) : _values = List.filled(length, 0);

  final List<int> _values;

  void unsigned(int start, int length, int value) {
    for (var offset = 0; offset < length; offset += 1) {
      final shift = length - offset - 1;
      _values[start + offset] = (value >> shift) & 1;
    }
  }

  void signed(int start, int length, int value) {
    unsigned(start, length, value < 0 ? (1 << length) + value : value);
  }

  void text(int start, int length, String value) {
    final padded = value.toUpperCase().padRight(length ~/ 6, '@');
    for (var index = 0; index < length ~/ 6; index += 1) {
      final encoded = _alphabet.indexOf(padded[index]);
      unsigned(start + index * 6, 6, encoded < 0 ? 32 : encoded);
    }
  }

  ({String payload, int fillBits}) payload() {
    final fillBits = (6 - _values.length % 6) % 6;
    final padded = [..._values, ...List.filled(fillBits, 0)];
    final output = StringBuffer();
    for (var index = 0; index < padded.length; index += 6) {
      var value = 0;
      for (var bit = 0; bit < 6; bit += 1) {
        value = (value << 1) | padded[index + bit];
      }
      output.writeCharCode(value < 40 ? value + 48 : value + 56);
    }
    return (payload: output.toString(), fillBits: fillBits);
  }
}
