/// Offline astronomical tide-height prediction.
///
/// The algorithm is a pure-Dart port of the MIT-licensed Neaps predictor at
/// commit 0f4f1523f25b3e78c6523afc544332683d795689. Harmonic data is the
/// bundled CC BY 4.0 TICON-4 subset generated by `tools/tides`.
///
/// These values are calculated context, not official tide tables or observed
/// water levels. They exclude wind, pressure, surge, waves and river flow.
library;

import 'dart:convert';
import 'dart:math' as math;

import 'package:flutter/services.dart';

import '../domain/marine_data.dart';
import '../domain/tide.dart';

const _degreesToRadians = math.pi / 180;
const _radiansToDegrees = 180 / math.pi;

class BundledHarmonicTideProvider implements TideProvider {
  BundledHarmonicTideProvider._({
    required Map<String, _StationData> stations,
    required this._catalogue,
    required this._clock,
  }) : _stations = Map.unmodifiable(stations);

  static const assetPath = 'assets/tides/solent_tides.json';
  static const warning =
      'Astronomical prediction only. Not official or observed; weather effects '
      'are not included.';

  static const MarineDataSource tideSource = MarineDataSource(
    id: 'ticon-4-neaps-solent',
    displayName: 'TICON-4 via Neaps',
    kind: MarineDataKind.prediction,
    authority: MarineDataAuthority.provider,
    licence: MarineDataLicence(
      name: 'CC BY 4.0',
      attribution:
          'TICON-4 harmonic data via the Neaps tide database (CC BY 4.0)',
      url: 'https://www.seanoe.org/data/00980/109129/',
      permitsOfflineCache: true,
      permitsCrewShare: true,
    ),
    coverageNote:
        'Curated Lymington, Portsmouth and Southampton reference stations.',
  );

  static Future<BundledHarmonicTideProvider> load({
    AssetBundle? bundle,
    DateTime Function()? clock,
  }) async => fromJson(
    await (bundle ?? rootBundle).loadString(assetPath),
    clock: clock,
  );

  static BundledHarmonicTideProvider fromJson(
    String source, {
    DateTime Function()? clock,
  }) {
    final decoded = jsonDecode(source);
    if (decoded is! Map<String, Object?> || decoded['schemaVersion'] != 1) {
      throw const FormatException('Unsupported bundled tide asset.');
    }
    final definitions = decoded['constituentDefinitions'];
    final stationValues = decoded['stations'];
    if (definitions is! List || stationValues is! List) {
      throw const FormatException('Bundled tide asset is incomplete.');
    }
    final catalogue = _ConstituentCatalogue.fromJson(definitions);
    final stations = <String, _StationData>{};
    for (final value in stationValues) {
      final data = _StationData.fromJson(value, catalogue);
      if (stations[data.station.id] != null) {
        throw FormatException('Duplicate tide station ${data.station.id}.');
      }
      stations[data.station.id] = data;
    }
    if (stations.isEmpty) {
      throw const FormatException('Bundled tide asset has no stations.');
    }
    return BundledHarmonicTideProvider._(
      stations: stations,
      catalogue: catalogue,
      clock: clock ?? DateTime.now,
    );
  }

  final Map<String, _StationData> _stations;
  final _ConstituentCatalogue _catalogue;
  final DateTime Function() _clock;

  @override
  MarineDataSource get source => tideSource;

  List<TideStation> get stations =>
      List.unmodifiable(_stations.values.map((value) => value.station));

  @override
  Future<List<TideStation>> stationsNear({
    required double latitude,
    required double longitude,
    double limitKilometers = 100,
  }) async {
    if (!latitude.isFinite ||
        !longitude.isFinite ||
        !limitKilometers.isFinite ||
        limitKilometers < 0) {
      throw ArgumentError('Station search needs finite coordinates and range.');
    }
    final matches =
        _stations.values
            .map(
              (data) => (
                station: data.station,
                distance: _distanceKilometers(
                  latitude,
                  longitude,
                  data.station.latitude,
                  data.station.longitude,
                ),
              ),
            )
            .where((item) => item.distance <= limitKilometers)
            .toList()
          ..sort((a, b) => a.distance.compareTo(b.distance));
    return List.unmodifiable(matches.map((item) => item.station));
  }

  @override
  Future<TidePrediction> predict({
    required TideStation station,
    required DateTime start,
    required DateTime end,
    Duration interval = const Duration(minutes: 10),
  }) async {
    final data = _stations[station.id];
    if (data == null) {
      throw ArgumentError('Unknown tide station ${station.id}.');
    }
    if (!start.isBefore(end)) {
      throw ArgumentError('Prediction start must be before end.');
    }
    if (interval.inSeconds <= 0) {
      throw ArgumentError.value(interval, 'interval', 'Must be positive.');
    }

    final stepSeconds = interval.inSeconds;
    final startSeconds = start.toUtc().millisecondsSinceEpoch ~/ 1000;
    final endSeconds = end.toUtc().millisecondsSinceEpoch ~/ 1000;
    final alignedStartSeconds = (startSeconds ~/ stepSeconds) * stepSeconds;
    final alignedEndSeconds =
        ((endSeconds + stepSeconds - 1) ~/ stepSeconds) * stepSeconds;
    final alignedStart = DateTime.fromMillisecondsSinceEpoch(
      alignedStartSeconds * 1000,
      isUtc: true,
    );
    final generatedAt = _clock().toUtc();
    final evaluator = _HarmonicEvaluator(
      station: data,
      catalogue: _catalogue,
      start: alignedStart,
      endHour: (alignedEndSeconds - alignedStartSeconds) / 3600,
    );
    final points = <MarineDatum<TideHeight>>[];
    for (
      var seconds = alignedStartSeconds;
      seconds <= alignedEndSeconds;
      seconds += stepSeconds
    ) {
      final at = DateTime.fromMillisecondsSinceEpoch(
        seconds * 1000,
        isUtc: true,
      );
      points.add(
        MarineDatum(
          value: TideHeight(
            meters: evaluator.heightAt((seconds - alignedStartSeconds) / 3600),
          ),
          source: tideSource,
          validAt: at,
          receivedAt: generatedAt,
          staleAfter: interval * 2,
          unit: 'm ${data.station.datum}',
          qualityNote:
              '${data.station.qualityNote ?? 'Quality not stated'}. '
              '$warning',
        ),
      );
    }
    return TidePrediction(
      station: data.station,
      points: points,
      extremes: _extremes(points, interval),
    );
  }
}

class _StationData {
  const _StationData({
    required this.station,
    required this.harmonics,
    required this.datumOffsetMeters,
  });

  factory _StationData.fromJson(
    Object? value,
    _ConstituentCatalogue catalogue,
  ) {
    if (value is! Map<String, Object?>) {
      throw const FormatException('Tide station is not an object.');
    }
    final id = _string(value, 'id');
    final datum = _string(value, 'chartDatum');
    final datums = value['datums'];
    final harmonicValues = value['harmonics'];
    if (datums is! Map || harmonicValues is! List) {
      throw FormatException('Station $id has no datums or harmonics.');
    }
    final msl = datums['MSL'];
    final chartDatum = datums[datum];
    if (msl is! num || chartDatum is! num) {
      throw FormatException('Station $id cannot transform MSL to $datum.');
    }
    final harmonics = <_Harmonic>[];
    for (final harmonicValue in harmonicValues) {
      if (harmonicValue is! Map<String, Object?>) {
        throw FormatException('Station $id has an invalid harmonic.');
      }
      final name = _string(harmonicValue, 'name');
      final definition = catalogue[name];
      if (definition == null) {
        throw FormatException('Station $id uses unknown constituent $name.');
      }
      harmonics.add(
        _Harmonic(
          definition: definition,
          amplitude: _number(harmonicValue, 'amplitude'),
          phaseDegrees: _number(harmonicValue, 'phase'),
        ),
      );
    }
    return _StationData(
      station: TideStation(
        id: id,
        name: _string(value, 'name'),
        latitude: _number(value, 'latitude'),
        longitude: _number(value, 'longitude'),
        datum: datum,
        source: BundledHarmonicTideProvider.tideSource,
        timeZone: value['timezone'] as String?,
        qualityNote: value['qualityNote'] as String?,
      ),
      harmonics: List.unmodifiable(harmonics),
      datumOffsetMeters: msl.toDouble() - chartDatum.toDouble(),
    );
  }

  final TideStation station;
  final List<_Harmonic> harmonics;
  final double datumOffsetMeters;
}

class _Harmonic {
  const _Harmonic({
    required this.definition,
    required this.amplitude,
    required this.phaseDegrees,
  });

  final _ConstituentDefinition definition;
  final double amplitude;
  final double phaseDegrees;
}

class _ConstituentDefinition {
  const _ConstituentDefinition({
    required this.name,
    required this.speedDegreesPerHour,
    required this.xdo,
    required this.nodalCode,
    required this.aliases,
    required this.explicitMembers,
  });

  final String name;
  final double speedDegreesPerHour;
  final List<int> xdo;
  final String nodalCode;
  final List<String> aliases;
  final List<(String, double)> explicitMembers;

  int get species => xdo.first;
}

class _ConstituentCatalogue {
  _ConstituentCatalogue._(this._byAlias);

  factory _ConstituentCatalogue.fromJson(List<Object?> values) {
    final definitions = <_ConstituentDefinition>[];
    for (final value in values) {
      if (value is! Map<String, Object?>) {
        throw const FormatException('Constituent definition is not an object.');
      }
      final rawXdo = value['xdo'];
      if (rawXdo is! List || rawXdo.length != 7) continue;
      final rawAliases = value['aliases'];
      final rawMembers = value['members'];
      definitions.add(
        _ConstituentDefinition(
          name: _string(value, 'name'),
          speedDegreesPerHour: _number(value, 'speed'),
          xdo: List.unmodifiable(rawXdo.map((item) => (item as num).toInt())),
          nodalCode: _string(value, 'nodalCorrection'),
          aliases: List.unmodifiable(
            rawAliases is List ? rawAliases.cast<String>() : const <String>[],
          ),
          explicitMembers: List.unmodifiable(
            rawMembers is List
                ? rawMembers.map((item) {
                    final pair = item as List;
                    return (pair[0] as String, (pair[1] as num).toDouble());
                  })
                : const <(String, double)>[],
          ),
        ),
      );
    }
    final aliases = <String, _ConstituentDefinition>{};
    for (final definition in definitions) {
      aliases[definition.name] = definition;
      for (final alias in definition.aliases) {
        aliases[alias] = definition;
      }
    }
    return _ConstituentCatalogue._(Map.unmodifiable(aliases));
  }

  final Map<String, _ConstituentDefinition> _byAlias;
  final Map<_ConstituentDefinition, List<(_ConstituentDefinition, double)>>
  _memberCache = {};

  _ConstituentDefinition? operator [](String name) => _byAlias[name];

  double equilibriumArgument(
    _ConstituentDefinition definition,
    _Astronomy astronomy,
  ) {
    final xdo = definition.xdo;
    final coefficients = [
      xdo[0],
      xdo[1] - 5,
      xdo[2] - 5,
      xdo[3] - 5,
      xdo[4] - 5,
      xdo[5] - 5,
      5 - xdo[6],
    ];
    final values = [
      astronomy.tau,
      astronomy.s,
      astronomy.h,
      astronomy.p,
      -astronomy.node,
      astronomy.solarPerigee,
      90.0,
    ];
    var result = 0.0;
    for (var index = 0; index < 7; index += 1) {
      result += coefficients[index] * values[index];
    }
    return result;
  }

  _Correction correction(
    _ConstituentDefinition definition,
    _Astronomy astronomy,
  ) {
    final fundamental = _fundamentalCorrection(definition.name, astronomy);
    if (fundamental != null) return fundamental;
    final members = _members(definition);
    var f = 1.0;
    var u = 0.0;
    for (final (member, factor) in members) {
      final value = correction(member, astronomy);
      u += factor * value.uDegrees;
      f *= math.pow(value.factor, factor.abs()).toDouble();
    }
    return _Correction(f, u);
  }

  List<(_ConstituentDefinition, double)> _members(
    _ConstituentDefinition definition,
  ) => _memberCache.putIfAbsent(definition, () {
    Iterable<(String, double)> names;
    if (definition.explicitMembers.isNotEmpty) {
      names = definition.explicitMembers;
    } else {
      names = switch (definition.nodalCode) {
        'z' || 'f' || 'y' => const [],
        'a' => const [('Mm', 1)],
        'm' => const [('M2', 1)],
        'o' => const [('O1', 1)],
        'k' => const [('K1', 1)],
        'j' => const [('J1', 1)],
        'b' => const [('M2', -1)],
        'c' => const [('M2', -2)],
        'g' => [('M2', definition.species / 2)],
        'p' => _decompose('2MN2', definition.species),
        'd' => _decompose('KQ1', definition.species),
        'q' => _decompose('NKM2', definition.species),
        'x' => _decompose(definition.name, definition.species),
        _ => throw FormatException(
          'Unknown nodal correction ${definition.nodalCode}.',
        ),
      };
    }
    return List.unmodifiable(
      names.map((item) {
        final member = _byAlias[item.$1];
        if (member == null) {
          throw FormatException('Missing constituent member ${item.$1}.');
        }
        return (member, item.$2);
      }),
    );
  });

  List<(String, double)> _decompose(String name, int species) {
    final match = RegExp(r'^(.+?)(\d+)$').firstMatch(name);
    if (match == null) return const [];
    final body = match.group(1)!;
    final target = species > 0 ? species : int.parse(match.group(2)!);
    final tokens = <(String, int)>[];
    var index = 0;
    while (index < body.length) {
      var multiplier = 0;
      while (index < body.length && _isDigit(body.codeUnitAt(index))) {
        multiplier = multiplier * 10 + body.codeUnitAt(index) - 48;
        index += 1;
      }
      if (multiplier == 0) multiplier = 1;
      if (index >= body.length || body[index] == '(') return const [];
      final letter = body.startsWith('lambda', index)
          ? 'lambda'
          : body.startsWith('nu', index)
          ? 'nu'
          : body[index];
      index += letter.length;
      tokens.add((letter, multiplier));
    }
    for (final kSpecies in [2, 1]) {
      final speciesValues = tokens
          .map((token) => _letterSpecies(token.$1, kSpecies))
          .toList();
      if (speciesValues.any((value) => value == null)) continue;
      if (tokens.length == 1) {
        final letterSpecies = speciesValues.first!;
        if (target > letterSpecies) {
          return [('${tokens.first.$1}$letterSpecies', target / letterSpecies)];
        }
        if (target == letterSpecies) {
          return [('${tokens.first.$1}$letterSpecies', 1)];
        }
      }
      final signs = List<int>.filled(tokens.length, 1);
      var total = 0;
      for (var i = 0; i < tokens.length; i += 1) {
        total += tokens[i].$2 * speciesValues[i]!;
      }
      for (var i = tokens.length - 1; i >= 0 && total != target; i -= 1) {
        signs[i] = -1;
        total -= 2 * tokens[i].$2 * speciesValues[i]!;
      }
      if (total != target) continue;
      return [
        for (var i = 0; i < tokens.length; i += 1)
          (
            '${tokens[i].$1}${speciesValues[i]}',
            (signs[i] * tokens[i].$2).toDouble(),
          ),
      ];
    }
    return const [];
  }
}

class _HarmonicEvaluator {
  _HarmonicEvaluator({
    required this.station,
    required this.catalogue,
    required this.start,
    required this.endHour,
  }) : _baseAstronomy = _Astronomy.at(start);

  final _StationData station;
  final _ConstituentCatalogue catalogue;
  final DateTime start;
  final double endHour;
  final _Astronomy _baseAstronomy;
  final Map<int, List<_Parameter>> _parametersByDay = {};

  double heightAt(double hour) {
    var result = station.datumOffsetMeters;
    for (final parameter in _parameters(hour)) {
      result +=
          parameter.amplitude *
          math.cos(parameter.speedRadiansPerHour * hour + parameter.phase);
    }
    return result;
  }

  List<_Parameter> _parameters(double hour) {
    final day = math.max(0, hour ~/ 24);
    return _parametersByDay.putIfAbsent(day, () {
      final chunkStart = day * 24.0;
      final chunkEnd = math.min(chunkStart + 24, endHour);
      final correctionTime = start.add(
        Duration(milliseconds: ((chunkStart + chunkEnd) * 1800000).round()),
      );
      final correctionAstronomy = _Astronomy.at(correctionTime);
      return List.unmodifiable(
        station.harmonics.where((value) => value.amplitude != 0).map((value) {
          final definition = value.definition;
          final correction = catalogue.correction(
            definition,
            correctionAstronomy,
          );
          return _Parameter(
            amplitude: value.amplitude * correction.factor,
            speedRadiansPerHour:
                definition.speedDegreesPerHour * _degreesToRadians,
            phase:
                (catalogue.equilibriumArgument(definition, _baseAstronomy) +
                    correction.uDegrees -
                    value.phaseDegrees) *
                _degreesToRadians,
          );
        }),
      );
    });
  }
}

class _Parameter {
  const _Parameter({
    required this.amplitude,
    required this.speedRadiansPerHour,
    required this.phase,
  });

  final double amplitude;
  final double speedRadiansPerHour;
  final double phase;
}

class _Correction {
  const _Correction(this.factor, this.uDegrees);

  final double factor;
  final double uDegrees;
}

_Correction? _fundamentalCorrection(String name, _Astronomy a) {
  final n = a.node * _degreesToRadians;
  final p = a.p * _degreesToRadians;
  final pp = a.solarPerigee * _degreesToRadians;
  return switch (name) {
    'Mm' => _Correction(
      1 -
          0.1311 * math.cos(n) +
          0.0538 * math.cos(2 * p) +
          0.0205 * math.cos(2 * p - n),
      0,
    ),
    'Mf' => _Correction(
      1.084 + 0.415 * math.cos(n) + 0.039 * math.cos(2 * n),
      -23.7 * math.sin(n) + 2.7 * math.sin(2 * n) - 0.4 * math.sin(3 * n),
    ),
    'O1' => _Correction(
      1.0176 + 0.1871 * math.cos(n) - 0.0147 * math.cos(2 * n),
      10.8 * math.sin(n) - 1.34 * math.sin(2 * n) + 0.19 * math.sin(3 * n),
    ),
    'K1' => _Correction(
      1.006 +
          0.115 * math.cos(n) -
          0.0088 * math.cos(2 * n) +
          0.0006 * math.cos(3 * n),
      -8.86 * math.sin(n) + 0.68 * math.sin(2 * n) - 0.07 * math.sin(3 * n),
    ),
    'J1' => _Correction(
      1.1029 +
          0.1676 * math.cos(n) -
          0.017 * math.cos(2 * n) +
          0.0016 * math.cos(3 * n),
      -12.94 * math.sin(n) + 1.34 * math.sin(2 * n) - 0.19 * math.sin(3 * n),
    ),
    'M1B' => _fromSinCos(
      2.783 * math.sin(2 * p) +
          0.558 * math.sin(2 * p - n) +
          0.184 * math.sin(n),
      1 +
          2.783 * math.cos(2 * p) +
          0.558 * math.cos(2 * p - n) +
          0.184 * math.cos(n),
    ),
    'M1C' || 'M1' => _fromSinCos(
      math.sin(p) + 0.2 * math.sin(p - n),
      2 * (math.cos(p) + 0.2 * math.cos(p - n)),
    ),
    'M1A' => _fromSinCos(
      -0.3593 * math.sin(2 * p) -
          0.2 * math.sin(n) -
          0.066 * math.sin(2 * p - n),
      1 +
          0.3593 * math.cos(2 * p) +
          0.2 * math.cos(n) +
          0.066 * math.cos(2 * p - n),
    ),
    'M2' => _Correction(
      1.0007 - 0.0373 * math.cos(n) + 0.0002 * math.cos(2 * n),
      -2.14 * math.sin(n),
    ),
    'K2' => _Correction(
      1.0246 +
          0.2863 * math.cos(n) +
          0.0083 * math.cos(2 * n) -
          0.0015 * math.cos(3 * n),
      -17.74 * math.sin(n) + 0.68 * math.sin(2 * n) - 0.04 * math.sin(3 * n),
    ),
    'M3' => () {
      final m2 = _fundamentalCorrection('M2', a)!;
      return _Correction(
        math.pow(math.sqrt(m2.factor), 3).toDouble(),
        -3.21 * math.sin(n),
      );
    }(),
    'L2' => _fromSinCos(
      -0.2505 * math.sin(2 * p) -
          0.1102 * math.sin(2 * p - n) -
          0.0156 * math.sin(2 * p - 2 * n) -
          0.037 * math.sin(n),
      1 -
          0.2505 * math.cos(2 * p) -
          0.1102 * math.cos(2 * p - n) -
          0.0156 * math.cos(2 * p - 2 * n) -
          0.037 * math.cos(n),
    ),
    'gamma2' => _fromSinCos(
      0.147 * math.sin(2 * (n - p)),
      1 + 0.147 * math.cos(2 * (n - p)),
    ),
    'alpha2' => _fromSinCos(
      -0.0446 * math.sin(p - pp),
      1 - 0.0446 * math.cos(p - pp),
    ),
    'delta2' => _fromSinCos(0.477 * math.sin(n), 1 - 0.477 * math.cos(n)),
    'xi2' ||
    'eta2' => _fromSinCos(-0.439 * math.sin(n), 1 + 0.439 * math.cos(n)),
    _ => null,
  };
}

_Correction _fromSinCos(double sinU, double cosU) => _Correction(
  math.sqrt(sinU * sinU + cosU * cosU),
  math.atan2(sinU, cosU) * _radiansToDegrees,
);

class _Astronomy {
  const _Astronomy({
    required this.s,
    required this.h,
    required this.p,
    required this.node,
    required this.solarPerigee,
    required this.tau,
  });

  factory _Astronomy.at(DateTime time) {
    final utc = time.toUtc();
    final centuries = (_julianDate(utc) - 2451545) / 36525;
    final s = _mod(_polynomial(_lunarLongitude, centuries), 360);
    final h = _mod(_polynomial(_solarLongitude, centuries), 360);
    final p = _mod(_polynomial(_lunarPerigee, centuries), 360);
    final node = _mod(_polynomial(_lunarNode, centuries), 360);
    final solarPerigee = _mod(_polynomial(_solarPerigee, centuries), 360);
    final tau = (_julianDate(utc) - _julianDate(utc).floor()) * 360 + h - s;
    return _Astronomy(
      s: s,
      h: h,
      p: p,
      node: node,
      solarPerigee: solarPerigee,
      tau: tau,
    );
  }

  final double s;
  final double h;
  final double p;
  final double node;
  final double solarPerigee;
  final double tau;
}

const _solarPerigee = [
  280.46645 - 357.5291,
  36000.76932 - 35999.0503,
  0.0003032 + 0.0001559,
  0.00000048,
];
const _solarLongitude = [280.46645, 36000.76983, 0.0003032];
const _lunarLongitude = [
  218.3164591,
  481267.88134236,
  -0.0013268,
  1 / 538841 - 1 / 65194000,
];
const _lunarNode = [
  125.044555,
  -1934.1361849,
  0.0020762,
  1 / 467410,
  -1 / 60616000,
];
const _lunarPerigee = [
  83.353243,
  4069.0137111,
  -0.0103238,
  -1 / 80053,
  1 / 18999000,
];

double _polynomial(List<double> coefficients, double argument) {
  var result = 0.0;
  for (var index = 0; index < coefficients.length; index += 1) {
    result += coefficients[index] * math.pow(argument, index);
  }
  return result;
}

double _julianDate(DateTime time) {
  var year = time.year;
  var month = time.month;
  final day =
      time.day +
      time.hour / 24 +
      time.minute / 1440 +
      time.second / 86400 +
      time.millisecond / 86400000;
  if (month <= 2) {
    year -= 1;
    month += 12;
  }
  final a = (year / 100).floor();
  final b = 2 - a + (a / 4).floor();
  return (365.25 * (year + 4716)).floor() +
      (30.6001 * (month + 1)).floor() +
      day +
      b -
      1524.5;
}

double _mod(double value, double divisor) =>
    ((value % divisor) + divisor) % divisor;

List<TideExtreme> _extremes(
  List<MarineDatum<TideHeight>> points,
  Duration interval,
) {
  final values = <TideExtreme>[];
  for (var index = 1; index < points.length - 1; index += 1) {
    final previous = points[index - 1].value.meters;
    final current = points[index].value.meters;
    final next = points[index + 1].value.meters;
    final high = current > previous && current >= next;
    final low = current < previous && current <= next;
    if (!high && !low) continue;
    final denominator = previous - 2 * current + next;
    final delta = denominator == 0
        ? 0.0
        : (0.5 * (previous - next) / denominator).clamp(-1.0, 1.0);
    final at = points[index].validAt.add(
      Duration(milliseconds: (interval.inMilliseconds * delta).round()),
    );
    final height = current - 0.25 * (previous - next) * delta;
    values.add(
      TideExtreme(
        kind: high ? TideExtremeKind.high : TideExtremeKind.low,
        height: TideHeight(meters: height),
        at: at,
      ),
    );
  }
  return List.unmodifiable(values);
}

double _distanceKilometers(
  double latitudeA,
  double longitudeA,
  double latitudeB,
  double longitudeB,
) {
  final latA = latitudeA * _degreesToRadians;
  final latB = latitudeB * _degreesToRadians;
  final dLat = (latitudeB - latitudeA) * _degreesToRadians;
  final dLon = (longitudeB - longitudeA) * _degreesToRadians;
  final value =
      math.sin(dLat / 2) * math.sin(dLat / 2) +
      math.cos(latA) * math.cos(latB) * math.sin(dLon / 2) * math.sin(dLon / 2);
  return 6371 * 2 * math.atan2(math.sqrt(value), math.sqrt(1 - value));
}

String _string(Map<String, Object?> value, String key) {
  final item = value[key];
  if (item is! String || item.trim().isEmpty) {
    throw FormatException('Missing string $key.');
  }
  return item;
}

double _number(Map<String, Object?> value, String key) {
  final item = value[key];
  if (item is! num || !item.toDouble().isFinite) {
    throw FormatException('Missing number $key.');
  }
  return item.toDouble();
}

bool _isDigit(int codeUnit) => codeUnit >= 48 && codeUnit <= 57;

int? _letterSpecies(String letter, int kSpecies) => switch (letter) {
  'M' || 'S' || 'N' || 'T' || 'R' || 'L' || 'nu' || 'lambda' => 2,
  'O' || 'P' || 'Q' || 'J' => 1,
  'K' => kSpecies,
  _ => null,
};
